# 选用配置
spring:
  profiles:
    active: dev

  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html

---
spring:
  profiles: dev
  ## 禁用模板缓存
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/develop
    username: root
    password: root

server:
  port: 8080

---
spring:
  profiles: online

server:
  port: 8080
